# Solution of;
# Project Euler Problem 29: Distinct powers
# https://projecteuler.net/problem=29
# 
# Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:22=4, 
# 23=8, 24=16, 25=3232=9, 33=27, 34=81, 35=24342=16, 43=64, 44=256, 
# 45=102452=25, 53=125, 54=625, 55=3125If they are then placed in numerical 
# order, with any repeats removed, we get the following sequence of 15 
# distinct terms:4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 
# 3125How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 
# 100 and 2 ≤ b ≤ 100?
# 
# by lcsm29 http://github.com/lcsm29/project-euler
import timed


def dummy(n):
    pass


if __name__ == '__main__':
    n = 1000
    i = 10000
    prob_id = 29
    timed.caller(dummy, n, i, prob_id)
