# Solution of;
# Project Euler Problem 45: Triangular, pentagonal, and hexagonal
# https://projecteuler.net/problem=45
# 
# Triangle, pentagonal, and hexagonal numbers are generated by the following 
# formulae:Triangle Tn=n(n+1)/2 1, 3, 6, 10, 15, . . . Pentagonal Pn=n(3n−1)/2 
# 1, 5, 12, 22, 35, . . . Hexagonal Hn=n(2n−1) 1, 6, 15, 28, 45, . . . It can 
# be verified that T285 = P165 = H143 = 40755. Find the next triangle number 
# that is also pentagonal and hexagonal.
# 
# by lcsm29 http://github.com/lcsm29/project-euler
import timed


def dummy(n):
    pass


if __name__ == '__main__':
    n = 1000
    i = 10000
    prob_id = 45
    timed.caller(dummy, n, i, prob_id)
