# Solution of;
# Project Euler Problem 288: An enormous factorial
# https://projecteuler.net/problem=288
# 
# For any prime p the number N(p,q) is defined byN(p,q) = ∑n=0 to q Tn*pn with 
# Tn generated by the following random number generator:S0 = 290797Sn+1 = Sn2 
# mod 50515093Tn = Sn mod pLet Nfac(p,q) be the factorial of N(p,q). Let 
# NF(p,q) be the number of factors p in Nfac(p,q). You are given that 
# NF(3,10000) mod 320=624955285. Find NF(61,107) mod 6110
# 
# by lcsm29 http://github.com/lcsm29/project-euler
import timed


def dummy(n):
   pass


if __name__ == '__main__':
   n = 1000
   i = 10000
   timed.caller(dummy, n, i)
